### ISSUE TITLE
US13 - read sub-project

### ISSUE THREAD

**Issue by Joachimle** [Aluna0001/EksamenKEA#16]
## User story
As a user I want to view a specific subproject so that I have an overview of its tasks.

## Acceptance criteria
+ The project page has a list of its subprojects' titles as links to each subproject with each subproject's total estimated time shown.
+ The project page shows the project's total estimated time.
+ The subproject page shows the subproject's title and total estimated time.
+ The subproject page has a list of its tasks' titles as links to each task with each task's total estimated time.
+ The subproject page has a feature that the user can use to return to the project page (the frontpage).

## Tasks
- [x] Add a view/get/read subproject method in Controller/Service/Repository.
- [x] Add GET endpoint /subproject/{subproject_id} to the view subproject method in Controller.
- [x] Add content to project and subproject templates.
- [x] Create Subproject class in model if absent.
- [x] Add unit tests of the three new methods.
