### ISSUE TITLE
US15 - read sub-task

### ISSUE THREAD

**Issue by Joachimle** [Aluna0001/EksamenKEA#18]
As a user I want to open a specific sub-task to see a time estimate.

Accept criteria:
- The browser can get a specific subtask by ID and show the title and time estimate
- Title and time estimate is retrieved through SQL

- [x] Create HTML template "sub-task"
- [ ] HTML template must show title and time estimate for the sub-task
- [x] Create controller GetMapping "/subtask/{subtaskid}
- [x] Create service method "getSubProject"
- [x] Create a repository method "readSubProject"
