### ISSUE TITLE
US1 - update project

### ISSUE THREAD

**Issue by esralund01** [Aluna0001/EksamenKEA#3]
## User story
As a user I want an edit button on the frontpage so that I can change the project title.
## Acceptance criteria
+ User can change the project title permanently and repeatedly in the browser.
## Tasks
- [x] Add 'edit' button to the project title on the frontpage.
- [x] Add GET and POST endpoints for title change to Controller.
- [x] Add get/read and update title methods to Service and Repository.
- [x] Unit test new methods.
