### ISSUE TITLE
US18 Error handling

### ISSUE THREAD

**Issue by zako0001** [Aluna0001/EksamenKEA#30]
## User story
As a user I want error handling of my choices so that I feel more safe and informed when navigating the web pages and when adding, changing, or deleting data.
## Acceptance criteria
+ All user input data must be handled in frontend so that no input causes unwanted effects.
## Tasks
- [x] Make sure all templates have the fittest input types.
- [x] Add as many restrictions to html inputs as possible.
- [x] Add default values to html inputs wherever sensible.
- [x] Make sure parameters in Controller methods are handled if they're not handled in the templates.
- [x] Add Controller exception handling.
