### ISSUE TITLE
US19 login

### ISSUE THREAD

**Issue by esralund01** [Aluna0001/EksamenKEA#37]
tasks ikke færdig
## User story
As a product owner I want a login page so access to my web app can be restricted to users with a user profile.
## Acceptance criteria
+ The frontpage is a login page.
+ Preregistered users can log in by filling in their username and password on the login page.
+ The entire web app except for the login page is inaccessible unless logged in.
## Tasks
- [ ] Create a login html template.
- [ ] Make the frontpage endpoint method in Controller return the login template.
- [ ] Add a POST endpoint login method in Controller sending username and password to Service login method.
- [ ] Add login method to Service.
- [ ] dvxgdfb
- [ ] dfbfdb
- [ ] sfb
