### ISSUE TITLE
US2 - delete sub-project

### ISSUE THREAD

**Issue by esralund01** [Aluna0001/EksamenKEA#4]
## User story
As a user I want a safe way to delete a subproject so that I can undo creating it only when I really mean to.
## Acceptance criteria
+ User must be able to delete a subproject by clicking on the web page.
+ Deletion must include a user confirmation step.
## Task
- [x] Add a 'delete' button to the subproject template.
- [x] Create a delete template with a confirmation step.
- [x] Add GET and POST methods for delete in Controller.
- [x] Add delete method in Service and Repository.
- [ ] Unit tests of new methods.
