### ISSUE TITLE
US6 - update sub-task

### ISSUE THREAD

**Issue by esralund01** [Aluna0001/EksamenKEA#8]
As a manager/project manager I want to be able to edit/update a sub-task, so it is adapted towards the needs of the product owner.

- [ ] Create a Get mapping for "updateSubTask" in Controller
- [ ] Create a Post mapping for "subTaskUpdated" in Controller
- [ ] Create update in Service
- [ ] Create update in Repo
- [ ] Create the HTML template "update_subtask"
- [ ] Update "subtask.html" template

Accept criteria:

- User must be able to edit a subtask's title and estimated hours
- The changes are saved
